version: '3'


services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile.prod
      container_name: "secure-encoder"
      ports:
        - "5000:5000"
      volumes:
        - ./:/src


      # volumes are not recomment in production env so please make sure to comment volumes when going to prod